package com.hpmt.cool100.dbhelp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CHILD_PARAMS.
 */
public class childParams {

    private Long id;
    private String defaultParam;
    private String rageParam;
    private String rageExplainParam;
    private String unitParam;
    private String explainParam;
    private String argsParam;
    private String paramID;
    private boolean isClick = false;

    public boolean isClick() {
		return isClick;
	}

	public void setClick(boolean isClick) {
		this.isClick = isClick;
	}

	public childParams() {
    }

    public childParams(Long id) {
        this.id = id;
    }

    public childParams(Long id, String defaultParam, String rageParam, String rageExplainParam, String unitParam, String explainParam, String argsParam, String paramID) {
        this.id = id;
        this.defaultParam = defaultParam;
        this.rageParam = rageParam;
        this.rageExplainParam = rageExplainParam;
        this.unitParam = unitParam;
        this.explainParam = explainParam;
        this.argsParam = argsParam;
        this.paramID = paramID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDefaultParam() {
        return defaultParam;
    }

    public void setDefaultParam(String defaultParam) {
        this.defaultParam = defaultParam;
    }

    public String getRageParam() {
        return rageParam;
    }

    public void setRageParam(String rageParam) {
        this.rageParam = rageParam;
    }

    public String getRageExplainParam() {
        return rageExplainParam;
    }

    public void setRageExplainParam(String rageExplainParam) {
        this.rageExplainParam = rageExplainParam;
    }

    public String getUnitParam() {
        return unitParam;
    }

    public void setUnitParam(String unitParam) {
        this.unitParam = unitParam;
    }

    public String getExplainParam() {
        return explainParam;
    }

    public void setExplainParam(String explainParam) {
        this.explainParam = explainParam;
    }

    public String getArgsParam() {
        return argsParam;
    }

    public void setArgsParam(String argsParam) {
        this.argsParam = argsParam;
    }

    public String getParamID() {
        return paramID;
    }

    public void setParamID(String paramID) {
        this.paramID = paramID;
    }

}
