package com.hpmt.cool100.dbhelp;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig childParamsDaoConfig;
    private final DaoConfig superParamDaoConfig;
    private final DaoConfig faultHelpDaoConfig;
    private final DaoConfig modifiParamDaoConfig;
    private final DaoConfig downLoadItemDaoConfig;

    private final childParamsDao childParamsDao;
    private final superParamDao superParamDao;
    private final faultHelpDao faultHelpDao;
    private final modifiParamDao modifiParamDao;
    private final downLoadItemDao downLoadItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        childParamsDaoConfig = daoConfigMap.get(childParamsDao.class).clone();
        childParamsDaoConfig.initIdentityScope(type);

        superParamDaoConfig = daoConfigMap.get(superParamDao.class).clone();
        superParamDaoConfig.initIdentityScope(type);

        faultHelpDaoConfig = daoConfigMap.get(faultHelpDao.class).clone();
        faultHelpDaoConfig.initIdentityScope(type);

        modifiParamDaoConfig = daoConfigMap.get(modifiParamDao.class).clone();
        modifiParamDaoConfig.initIdentityScope(type);

        downLoadItemDaoConfig = daoConfigMap.get(downLoadItemDao.class).clone();
        downLoadItemDaoConfig.initIdentityScope(type);

        childParamsDao = new childParamsDao(childParamsDaoConfig, this);
        superParamDao = new superParamDao(superParamDaoConfig, this);
        faultHelpDao = new faultHelpDao(faultHelpDaoConfig, this);
        modifiParamDao = new modifiParamDao(modifiParamDaoConfig, this);
        downLoadItemDao = new downLoadItemDao(downLoadItemDaoConfig, this);

        registerDao(childParams.class, childParamsDao);
        registerDao(superParam.class, superParamDao);
        registerDao(faultHelp.class, faultHelpDao);
        registerDao(modifiParam.class, modifiParamDao);
        registerDao(downLoadItem.class, downLoadItemDao);
    }
    
    public void clear() {
        childParamsDaoConfig.getIdentityScope().clear();
        superParamDaoConfig.getIdentityScope().clear();
        faultHelpDaoConfig.getIdentityScope().clear();
        modifiParamDaoConfig.getIdentityScope().clear();
        downLoadItemDaoConfig.getIdentityScope().clear();
    }

    public childParamsDao getChildParamsDao() {
        return childParamsDao;
    }

    public superParamDao getSuperParamDao() {
        return superParamDao;
    }

    public faultHelpDao getFaultHelpDao() {
        return faultHelpDao;
    }

    public modifiParamDao getModifiParamDao() {
        return modifiParamDao;
    }

    public downLoadItemDao getDownLoadItemDao() {
        return downLoadItemDao;
    }

}
