package com.hpmt.cool100.dbhelp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DOWN_LOAD_ITEM.
 */
public class downLoadItem {

    private Long id;
    private String downName;
    private String date;
    private String times;
    private String dwTag;

    public downLoadItem() {
    }

    public downLoadItem(Long id) {
        this.id = id;
    }

    public downLoadItem(Long id, String downName, String date, String times, String dwTag) {
        this.id = id;
        this.downName = downName;
        this.date = date;
        this.times = times;
        this.dwTag = dwTag;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDownName() {
        return downName;
    }

    public void setDownName(String downName) {
        this.downName = downName;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getTimes() {
        return times;
    }

    public void setTimes(String times) {
        this.times = times;
    }

    public String getDwTag() {
        return dwTag;
    }

    public void setDwTag(String dwTag) {
        this.dwTag = dwTag;
    }

}
