package com.hpmt.cool100.dbhelp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table MODIFI_PARAM.
 */
public class modifiParam {

    private Long id;
    private String name;
    private String contain;
    private String value;
    private String downloadtag;

    public modifiParam() {
    }

    public modifiParam(Long id) {
        this.id = id;
    }

    public modifiParam(Long id, String name, String contain, String value, String downloadtag) {
        this.id = id;
        this.name = name;
        this.contain = contain;
        this.value = value;
        this.downloadtag = downloadtag;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getContain() {
        return contain;
    }

    public void setContain(String contain) {
        this.contain = contain;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public String getDownloadtag() {
        return downloadtag;
    }

    public void setDownloadtag(String downloadtag) {
        this.downloadtag = downloadtag;
    }

    @Override
    public boolean equals(Object o) {
    	// TODO Auto-generated method stub
    	if (o instanceof modifiParam) {
    		modifiParam m = (modifiParam) o;
			return this.name.equals(m.getName());
		}
    	
    	
    	return super.equals(o);
    }
    
}
