package com.hpmt.cool100.dbhelp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SUPER_PARAM.
 */
public class superParam {

    private Long id;
    private String explainParam;
    private String argsParam;
    private String paramID;

    public superParam() {
    }

    public superParam(Long id) {
        this.id = id;
    }

    public superParam(Long id, String explainParam, String argsParam, String paramID) {
        this.id = id;
        this.explainParam = explainParam;
        this.argsParam = argsParam;
        this.paramID = paramID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getExplainParam() {
        return explainParam;
    }

    public void setExplainParam(String explainParam) {
        this.explainParam = explainParam;
    }

    public String getArgsParam() {
        return argsParam;
    }

    public void setArgsParam(String argsParam) {
        this.argsParam = argsParam;
    }

    public String getParamID() {
        return paramID;
    }

    public void setParamID(String paramID) {
        this.paramID = paramID;
    }

}
